import Link from "next/link";
import { redirect } from "next/navigation";
import { createClient } from "@/lib/supabase/server";
import { TestHistory } from "@/components/tests/test-history";
import { TestsHome } from "@/components/mobile/tests-home";
import type { TestRecord } from "@/types/ai-studio";

export const metadata = { title: "AI Tests" };
export const dynamic = "force-dynamic";

/** History page: every generated test with resume / retake / review / delete. */
export default async function TestsPage() {
  const supabase = await createClient();
  const { data: { user } } = await supabase.auth.getUser();
  if (!user) redirect("/login?next=/tests");

  // Skip the heavy questions/answers JSON — the list only needs metadata.
  const { data: tests } = await supabase
    .from("ai_tests")
    .select("id, title, exam, exam_name, status, score, total_marks, created_at, completed_at, config")
    .order("created_at", { ascending: false })
    .limit(100);

  return (
    <main className="min-h-dvh px-6 py-10 bg-gradient-to-b from-white via-brand-50 to-white dark:from-[#0b0f1a] dark:via-[#131a2e] dark:to-[#0b0f1a]">
      <div className="mx-auto max-w-3xl">
        <Link href="/dashboard" className="text-sm text-slate-500 hover:text-brand-500">← Dashboard</Link>
        <h1 className="mt-1 text-3xl font-extrabold">AI Test Generator</h1>
        <p className="mt-1 text-sm text-slate-500 dark:text-slate-400">
          NEET · JEE · KCET · Boards · UPSC · SSC — full mock papers generated by AI, graded instantly.
        </p>
        <TestsHome tests={(tests ?? []) as Partial<TestRecord>[] as TestRecord[]} />
        <div id="test-history" className="mt-8 scroll-mt-24">
          <TestHistory initial={(tests ?? []) as Partial<TestRecord>[] as TestRecord[]} />
        </div>
      </div>
    </main>
  );
}
